apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: poc-loki-and-promtail
build:
  artifacts:
    - image: my-app-1
      custom:
        buildCommand: ./scripts/build-my-app-1.sh
    - image: my-app-2
      custom:
        buildCommand: ./scripts/build-my-app-2.sh
deploy:
  kubectl:
    manifests:
      - manifests/*.yaml
  helm:
   releases:
     - name: promptail
       chartPath: loki/promtail
       skipBuildDependencies: true
       valuesFiles:
        - myvals.yaml
       setValues:
         loki:
           serviceName: loki

portForward:
  - resourceType: Service
    resourceName: grafana
    port: 3000
    localPort: 3000
  - resourceType: Service
    resourceName: loki
    port: 3100
    localPort: 3100
  - resourceType: Service
    resourceName: poc
    port: 3000
    localPort: 3001
  - resourceType: Daemonset
    resourceName: promptail-promtail
    port: 3101
    localPort: 3101
