apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app-2
  name: my-app-2
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: my-app-2
status:
  loadBalancer: {}
