image:
  tag: 1.6.1
livenessProbe: []
readinessProbe: []
scrapeConfigs:
  - job_name: kubernetes-pods
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            output: msg
            level: level
            timestamp: time
      - timestamp:
          source: timestamp
          format: Unix
          action_on_failure: skip
      - labels:
          level:
      - output:
          source: output
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        regex: "my-app-.*"
        source_labels:
          - __meta_kubernetes_pod_label_app
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - replacement: /var/log/pods/*$1*/*/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
        target_label: __path__
config:
  client:
    url: http://loki:3100/loki/api/v1/push
    # Maximum wait period before sending batch
    batchwait: 1s
    # Maximum batch size to accrue before sending, unit is byte
    batchsize: 102400

    # Maximum time to wait for server to respond to a request
    timeout: 10s

    backoff_config:
      # Initial backoff time between retries
      min_period: 100ms
      # Maximum backoff time between retries
      max_period: 5s
      # Maximum number of retries when sending batches, 0 means infinite retries
      max_retries: 20

    # The labels to add to any time series or alerts when communicating with loki
    external_labels: {}

  server:
    http_listen_port: 3101

  positions:
    filename: /run/promtail/positions.yaml
  target_config:
    # Period to resync directories being watched and files being tailed
    sync_period: 10s